### PR TITLE
Fixed login procedure

### PR DESCRIPTION
**Pull request by realmayus**
Memrise made significant changes to its login procedure, rendering this plugin broken. I completely revamped the sign in code so that it works again. The download code still works as of now.

### CODE REVIEW

**Comment by wilddom** [comment]
Thank you! I do have two questions though:

1. Did you really have problems with the old login method or did you implement this for the future? Because actually the old login method still seems to work for me. But either way it's definitely great to have a working implementation.

2. Are you sure that the requests module is part of the Anki distribution? I got some complaints from Windows users in the past about missing modules.

**Comment by realmayus** [comment]
1. Yeah, someone asked me if I could look into it and after deleting the cookies of the extension I was able to confirm that the login system doesn't work anymore, because memrise apparently shut down the /login endpoint 
2. I'll have to check this, if it's not part of Anki I can see if I get it to work with the same packages you were using 👍

**Comment by realmayus** [comment]
Hmm, I just checked again and it looks like the https://app.memrise.com/login/ endpoint works again. I'll have to confirm this though

**Comment by wilddom** [comment]
Okay, the old login endpoint doesn't seem to be stable: #95

**Comment by Digital-Coder** [comment]
@realmayus I tried your commit for possible solution ,but I still got error mentioned here  #102. But it seems its only failing on large downloads like 5000+ notes

**Comment by wilddom** [comment]
> @realmayus I tried your commit for possible solution ,but I still got error mentioned here #102. But it seems its only failing on large downloads like 5000+ notes

The mentioned issue is not related to the login procedure.

**Pull request merged**
